[package]
name = "the_rust_book_in_a_nutshell_lessons"
version = "0.1.0"
edition = "2021"
description = "Lessons of the Rust book in a nutshell"
license = "MIT"

[dependencies]
color-eyre = "0.6.2"
rand = "0.8.5"
